### ISSUE TITLE
Snapshot 'root' not present in /root/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2

### ISSUE THREAD

**Issue by ghost** [AndrewFasano/tenet_tracer#1]
when i follow you advice, I got this error. and you help me solve this error  

root@1711ddb0eda3:/panda# python run.py x86_64 /home/trace/tenet_tracer_modify/testdir  ls -al
using generic x86_64
Loading libpanda from /panda/build
os_name=[linux-64-ubuntu:4.15.0-72-generic-noaslr-nokaslr]
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu:4.15.0-72-generic-noaslr-nokaslr
[PYPANDA] Panda args: [/panda/build/x86_64-softmmu/libpanda-x86_64.so -L /panda/build/pc-bios /root/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 -display none -m 1024 -serial unix:/tmp/pypanda_s2e65fnhc,server,nowait -monitor unix:/tmp/pypanda_mxo0gp6jd,server,nowait]
PPP automatically loaded plugin proc_start_linux
PANDA[core]:loading required plugin proc_start_linux
PANDA[core]:initializing proc_start_linux
PANDA[core]:loading required plugin syscalls2
PANDA[core]:initializing syscalls2
PANDA[syscalls2]:using profile for linux x64 64-bit
PANDA[core]:loading required plugin hooks
PANDA[core]:initializing hooks
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    panda.run()
  File "/panda/panda/python/core/pandare/panda.py", line 536, in run
    raise saved_exception
  File "/panda/panda/python/core/pandare/panda.py", line 934, in wrapper
    f()
  File "/panda/panda/python/core/pandare/utils.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "run.py", line 45, in driver
    panda.revert_sync("root")
  File "/panda/panda/python/core/pandare/utils.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "/panda/panda/python/core/pandare/panda.py", line 2324, in revert_sync
    raise ValueError(f"Snapshot '{snapshot_name}' not present in {self.qcow}")
ValueError: Snapshot 'root' not present in /root/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2
root@1711ddb0eda3:/panda#

**Comment by AndrewFasano** [comment]
There's a chance your snapshot file got corrupted - if you delete it, it should re-download it for you automatically.
